### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Tiny2SqueezeContent)
add_subdirectory(Tiny2Squeeze)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Tiny2SqueezeContentplugin
    Tiny2Squeezeplugin)